accept yaml files

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -37,37 +37,37 @@ runs:
       shell: bash
       id: get_image
 
-    - name: Mount image
-      run: |
-          sudo --preserve-env bash "${GITHUB_ACTION_PATH}/mount_image.sh" "${{ steps.get_image.outputs.image }}" "${{ inputs.additional_mb }}" "${{ inputs.minimum_free_mb }}" "${{ inputs.root_partition }}"
-      shell: bash
-      id: mount_image
+    # - name: Mount image
+    #   run: |
+    #       sudo --preserve-env bash "${GITHUB_ACTION_PATH}/mount_image.sh" "${{ steps.get_image.outputs.image }}" "${{ inputs.additional_mb }}" "${{ inputs.minimum_free_mb }}" "${{ inputs.root_partition }}"
+    #   shell: bash
+    #   id: mount_image
 
-    - name: Run commands
-      run: |
-          echo "Running the commands"
-          chroot_scriptdir=/tmp/build
-          scriptdir="${{ env.rootdir }}${chroot_scriptdir}"
-          sudo mkdir --parents "${scriptdir}"
-          sudo mount --bind "${{ github.workspace }}" "${scriptdir}"
+    # - name: Run commands
+    #   run: |
+    #       echo "Running the commands"
+    #       chroot_scriptdir=/tmp/build
+    #       scriptdir="${{ env.rootdir }}${chroot_scriptdir}"
+    #       sudo mkdir --parents "${scriptdir}"
+    #       sudo mount --bind "${{ github.workspace }}" "${scriptdir}"
 
-          cat >> "${scriptdir}/commands.sh" << EOF
-          #!/bin/bash
-          # set -exo pipefail
-          # export SHELLOPTS
-          # export BASHOPTS
-          cd "${chroot_scriptdir}"
-          ${{ inputs.commands }}
-          EOF
+    #       cat >> "${scriptdir}/commands.sh" << EOF
+    #       #!/bin/bash
+    #       # set -exo pipefail
+    #       # export SHELLOPTS
+    #       # export BASHOPTS
+    #       cd "${chroot_scriptdir}"
+    #       ${{ inputs.commands }}
+    #       EOF
 
-          sudo chmod +x "${scriptdir}/commands.sh"
+    #       sudo chmod +x "${scriptdir}/commands.sh"
 
-          sudo --preserve-env chroot "${{ env.rootdir }}" bash -c "${chroot_scriptdir}/commands.sh"
-      shell: bash
-      id: run_commands
+    #       sudo --preserve-env chroot "${{ env.rootdir }}" bash -c "${chroot_scriptdir}/commands.sh"
+    #   shell: bash
+    #   id: run_commands
 
-    - name: Clean up and pack image
-      run: |
-          sudo --preserve-env bash ${GITHUB_ACTION_PATH}/pack_image.sh "${{ steps.get_image.outputs.image }}"
-      shell: bash
-      id: pack_image
+    # - name: Clean up and pack image
+    #   run: |
+    #       sudo --preserve-env bash ${GITHUB_ACTION_PATH}/pack_image.sh "${{ steps.get_image.outputs.image }}"
+    #   shell: bash
+    #   id: pack_image
